### ISSUE TITLE
Wrong size for extra data

### ISSUE THREAD

**Issue by tjaynl** [flathub/gg.guilded.Guilded#9]
I'm trying to install Guilded on Fedora with Flatpak but when i try to it gives me the following error:

error: Failed to install gg.guilded.Guilded: Wrong size for extra data https://www.guilded.gg/downloads/Guilded-Linux.deb

How can we solve this?

**Comment by TysonChickens** [comment]
Same here. I double-checked the file size for the Guilded-Linux.deb `86632330`  and verified sha256 `0b29f5fa9bdb275ec32cf905abd83c9f3fa157a02d7813fc87b842f307bcbd47` is all good with the manifest file. I remember the flatpak install used to work a few months ago. Still trying to understand what changed.

Also in terminal before error: ` 1. [✗] gg.guilded.Guilded          stable         i          flathub         86.6 MB / 88.1 MB`

**Comment by losuler** [comment]
It looks like there must have been some sort of momentary networking issue on Flathub's end, because unbeknownst to me, the release build failed https://flathub.org/builds/#/builders/32/builds/80383 (despite the test build moments before passing).

Either way, I've rebuilt https://flathub.org/builds/#/builders/32/builds/82674 and published https://flathub.org/builds/#/builders/29/builds/44784 the release and it should show up on Flathub in the next few hours.

I'll ensure I make note of this so I can catch these types of errors in the future.

**Comment by JoshTheBlack** [comment]
This issue has returned for me.  Unable to install with the error:

`Failed to install gg.guilded.Guilded: Wrong size for extra data https://www.guilded.gg/downloads/Guilded-Linux.deb
`
